server:
  port: 8001
  servlet:
    context-path: /system

spring:
  application:
    name: system

  #数据源、连接池配置
  datasource:
    url: jdbc:mysql://47.111.141.110:3306/myProject?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.111.141.110
    port: 6379


eureka:
  client:
    #作为客户端，不进行服务注册、服务发现
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  #暴露ip地址
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


#mybatisPlus配置
mybatis-plus:
  type-enums-package: com.yh.system.domain.enums

#logback
logging:
  level:
    com.yh.system.mapper: debug

#swagger是否开启
swagger:
  enabled: true

##springboot任务模块是否开启
scheduling:
  enabled: false

#文件服务器
fileUpload:
  domain: http://localhost:80/download/
  dir: D://data/



