server:
  port: 8001
spring:
  application:
    name: system

eureka:
  client:
    #作为客户端，不进行服务注册、服务发现
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

  #暴露ip地址
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1






