#数据源、连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.111.141.110:3306/myProject?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: yuanhuan123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
        slf4j:
          enabled: true


  redis:
    host: 47.111.141.110
    port: 6379
    password: yh9527
    database: 0
    lettuce:
      pool:
        min-idle: 1
        max-active: 8
        max-idle: 8
        max-wait: 3000
    timeout: 5000

#logback
logging:
  level:
    com.yh.system.mapper: debug

#swagger是否开启
swagger:
  enabled: true

##springboot任务模块是否开启
scheduling:
  enabled: false

#websocket模块开启
websocket:
  enabled: true

#文件服务器
file-upload:
  domain: http://localhost:80/download/
  dir: D://data/
