#数据源、连接池配置
spring:
  datasource:
    url: jdbc:mysql://47.111.141.110:3306/myProject?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.111.141.110
    port: 6379
    password: yh9527

#logback
logging:
  level:
    com.yh.system.mapper: debug

#swagger是否开启
swagger:
  enabled: true

#springboot任务模块是否开启
scheduling:
  enabled: false

#websocket时候开启(如果使用外部tomcat,则默认开启)
websocket:
  enabled: true

#文件服务器
fileUpload:
  domain: http://localhost:80/download/
  dir: D://data/